### ISSUE TITLE
How to specify ssh key?

### ISSUE THREAD

**Issue by leemalmac** [ndenev/mpssh#26]
I use `-i` option with ssh, to set which ssh key to use for connection. How can I do the same with mpssh?

**Comment by ndenev** [comment]
Sorry, there is no way to set the key used in `mpssh`, but maybe that's something that you can put in `.ssh/config` to set which key is used for which host, or better yet run an `ssh-agent`?

**Comment by leemalmac** [comment]
Shame on me. Ssh config solved issue. Thanks!
