### ISSUE TITLE
Allow user to specify identity file

### ISSUE THREAD

**Issue by ethomas2** [ndenev/mpssh#27]
I would like to mpssh into many machines using a different identity file than my default one. I.e, instead of sshing into machines using the default private key `~/.ssh/id_rsa` I would like to provide a specific private key `~/.ssh/other_id_rsa`.

With `ssh`, this can be accomplished using the `-i` option. `ssh -i ~/.ssh/other_id_rsa my-host.com`

More generally, it would be nice to be able to pass in arbitrary parameters to the underlying ssh processes. The only use case I have right now is for the `-i` option, but I could see many other options potentially being useful in the future, especially the `-o` option (actually `-o IdentityFile=foo` would replace the need for `-i`)

**Comment by ethomas2** [comment]
Made a pull request (just for `-i`, not for `-o`)

#28

**Comment by ndenev** [comment]
I agree, `-o` sounds better, but for now I've merged the PR for the `-i` option.

Thanks
